Add totalview@2020.3.11 for BB5
BlueBrain/spack pull request #1141
Opened 2021-04-29 08:07 UTC by pramodk

* add new package version for totalview
 * change mirror handling : rsync whole mirror dir
 * enable totalview module

Tarball has been added to:

```
/gpfs/bbp.cscs.ch/ssd/apps/hpc/download/totalview/
```

2021-04-29 11:43 UTC, matz-e commented on deploy/environments/externals.yaml
> +    - totalview@2020.3.11
Shouldn't we remove the version to always grab the latest?

2021-04-30 07:12 UTC, matz-e requested changes

2021-04-30 07:12 UTC, matz-e commented on var/spack/repos/builtin/packages/totalview/package.py
> +        url='file:///gpfs/bbp.cscs.ch/apps/hpc/download/totalview/totalview_2021.1.16_linux_x86-64.tar',
```suggestion
        url='file://{0}/totalview_2020.3.11_linux_x86-64.tar'.format(mirror_dir),
```

2021-05-01 09:09 UTC, pramodk commented
Mirror in env might need different handling: https://spack.readthedocs.io/en/latest/mirrors.html#mirror-environment

2021-05-04 13:04 UTC, matz-e commented
Some conclusions:
* Package downloads on the mirror need to be of form `{mirrror_url}/{package_name}/{package_name}-{version}.tar`
* Resource downloads on the mirror need to be of form `{mirror_url}/{package_name}/{arch}-{version}.tar`

Got stuff to build with a mirror setup where the `totalview` directory looked like:
```
-rw-r--r-- 1 matwolf bbp       950 May  4 14:46 totalview.2020.3.11.md5sum
-rw-r--r-- 1 matwolf bbp 253839360 May  4 14:46 x86_64-2021.1.16.tar
-rw-r--r-- 1 matwolf bbp       950 May  4 14:46 totalview.2021.1.16.md5sum
-rw-r--r-- 1 matwolf bbp  28057600 May  4 14:46 totalview.2020.3.11.tar
-rw-r--r-- 1 matwolf bbp   1001091 May  4 14:46 totalview.2020.3-release_notes.pdf
-rw-r--r-- 1 matwolf bbp 249026560 May  4 14:46 totalview_2020.3.11_linux_x86-64.tar
-rw-r--r-- 1 matwolf bbp  29163520 May  4 14:46 totalview-2021.1.16.tar
-rw-r--r-- 1 matwolf bbp    436714 May  4 14:46 totalview.2021.1-release_notes.pdf
```

2021-05-05 11:16 UTC, matz-e commented
Files on the mirror have been adjusted.

Retest this please.

2021-05-05 11:42 UTC, matz-e approved these changes
All good from my side.

2021-05-05 11:43 UTC, iomaganaris approved these changes

2021-06-20 21:20 UTC, pramodk commented
@matz-e : didn't realise this was pending. I will merge this now as there are no conflicts. Lets see if something else will fail.

2021-06-20 21:21 UTC, merged