Update Spykfunc package to latest master
BlueBrain/spack pull request #1211
Opened 2021-06-24 09:31 UTC by sergiorg-hpc

The recent changes in Spykfunc are required in order to fix certain out-of-memory and timeout errors, among others.

This PR is related to https://github.com/BlueBrain/spack/pull/1205.

2021-06-24 12:42 UTC, sergiorg-hpc commented
The deployment CI has failed because there are some short of weird dependencies set in different parts, and we need to unify everything here in the recipe. For instance:

https://github.com/BlueBrain/spack/pull/1162/files#diff-5fb5801bf99d169e881f6810e691465a7ac814314fa7394a7c48fe546fc5cc9cR70

I also find it odd that we explicitly set version ranges. It should be more like `@0.15.1:`, and not `@0.15.1:0.16.0`, unless the following version do not need this. Just my opinion.

2021-06-25 07:09 UTC, matz-e requested changes
This will break the toolchain due to commit `b9c1816d49cb773aea682d9cb071439284bc32f1`.

It would be better to either take the fixing commit and apply it as a patch or backport it to a `bugfix/0.16` branch and release `0.16.1`

2021-06-25 15:22 UTC, matz-e commented on var/spack/repos/builtin/packages/spykfunc/package.py
> +    patch('bogus-h5py.patch', when='@0.15.2:0.16.1')
```suggestion
    patch('bogus-h5py.patch', when='@0.15.2:0.16.0.0')
```

2021-06-26 12:24 UTC, sergiorg-hpc commented
Finally the CI passed and the correct version has been deployed. I needed to run yesterday the `incubator.spack-deployment` to manually clean-up everything, and now the version `0.16.0.20210624` is visible on BB5.

2021-07-09 12:40 UTC, sergiorg-hpc commented
The final PR is located here:
https://github.com/BlueBrain/spack/pull/1222

2021-07-09 12:40 UTC, closed without merging