Rel with deb info and assert
BlueBrain/spack pull request #1368
Opened 2021-11-17 16:21 UTC by nico-canta

Here I included the new `build_type` and set the default value `default="RelWithDebInfoAndAssert"`.
There are also some old (and unrelated) changes.  Let me know if they could be useful or should be removed from this PR.

2021-11-17 16:40 UTC, matz-e requested changes

2021-11-17 16:40 UTC, matz-e commented on var/spack/repos/builtin/packages/neuron/package.py
> +        args.append('-DCMAKE_PREFIX_PATH=/usr/X11')
```suggestion
```

2021-11-18 10:33 UTC, matz-e commented
I'd prefer if the PR title starts with the relevant package name, so here `steps: `, too :)

2021-11-18 10:37 UTC, nico-canta commented
`var/spack/repos/builtin/packages/steps/package.py:32: [E501] line too long (99 > 79 characters)`

I don't understand this error. I can see other lines that are longer than 79 characters. Is it something else?

2021-11-18 10:45 UTC, nico-canta commented
@tristan0x I set the default `build_type` to "Release" also here.

2021-11-18 10:45 UTC, matz-e commented
> `var/spack/repos/builtin/packages/steps/package.py:32: [E501] line too long (99 > 79 characters)`
> 
> I don't understand this error. I can see other lines that are longer than 79 characters. Is it something else?

I think sha lines are allowed to exceed that. But this particular line can be broken up properly.

2021-11-18 10:59 UTC, tristan0x requested changes

2021-11-18 10:59 UTC, tristan0x commented on var/spack/repos/builtin/packages/gmsh/package.py
> +    version('4.8.4', sha256='760dbdc072eaa3c82d066c5ba3b06eacdd3304eb2a97373fe4ada9509f0b6ace')
Should not be part of this change.
```suggestion
```

2021-11-18 11:20 UTC, matz-e requested changes

2021-11-18 11:20 UTC, matz-e commented on var/spack/repos/builtin/packages/steps/package.py
> +            values=("Debug", "Release", "RelWithDebInfo", "MinSizeRel",
```suggestion
            values=("Debug", "Release", "RelWithDebInfo", "MinSizeRel",
```

2021-11-18 14:00 UTC, tristan0x requested changes

2021-11-18 14:00 UTC, tristan0x commented on var/spack/repos/builtin/packages/steps/package.py
> +    variant("build_type", default="Release", description="CMake build type",
Keep previous spack default
```suggestion
    variant("build_type", default="RelWithDebInfo", description="CMake build type",
```

2021-11-18 14:13 UTC, matz-e commented
Could you rebase on top of the latest `develop`, please?

2021-11-18 15:37 UTC, matz-e approved these changes

2021-11-19 09:21 UTC, tristan0x approved these changes
LGTM

2021-11-19 09:22 UTC, merged