coreneuron: Bumps to v8.2.1
BlueBrain/spack pull request #1679
Opened 2022-08-29 14:09 UTC by sergiorg-hpc

2022-08-29 14:10 UTC, olupton approved these changes

2022-08-29 14:11 UTC, pramodk approved these changes, later dismissed

2022-08-29 14:19 UTC, matz-e submitted a review, later dismissed

2022-08-29 14:23 UTC, alexsavulescu submitted a review, later dismissed

2022-08-29 14:27 UTC, olupton requested changes
Actually
```python
conflicts('+shared', when='@:8.2.0 +gpu')
```
is not correct :/

2022-08-29 14:35 UTC, sergiorg-hpc commented
> 

Is it because of the version? If so, perhaps this simply could work for now, what do you think?:
```
conflicts('+shared', when='+gpu')
```

2022-08-29 14:37 UTC, olupton commented
We want to allow `coreneuron@develop +gpu+shared` for use in CI pipelines.
I don't think this will be supported in any pre-9.0 release, so we could change the upper end of the range...but perhaps this conflict is doing more harm than good, seeing as pre-9.0 versions will just silently ignore +shared anyway when +gpu is passed... (cc: @iomaganaris )

2022-08-29 15:17 UTC, iomaganaris commented
> We want to allow `coreneuron@develop +gpu+shared` for use in CI pipelines. I don't think this will be supported in any pre-9.0 release, so we could change the upper end of the range...but perhaps this conflict is doing more harm than good, seeing as pre-9.0 versions will just silently ignore +shared anyway when +gpu is passed... (cc: @iomaganaris )

Since the PR related to `+gpu+shared` has been already merged, I expect the next `CoreNEURON` tag to be based on top of it, so maybe:
```
conflicts('+shared', when='@:8.2.1 +gpu')
```
is enough?

2022-08-30 07:46 UTC, sergiorg-hpc commented
> Since the PR related to `+gpu+shared` has been already merged, I expect the next `CoreNEURON` tag to be based on top of it, so maybe:
> 
> ```
> conflicts('+shared', when='@:8.2.1 +gpu')
> ```
> 
> is enough?

I have the suspicion that this will be a problem if, for some reason, there is a 8.2.2 release or similar. Based on @olupton's comment, I just changed it to be `@:8.9.9` to prevent future issues with this.

Sounds good?

2022-08-30 07:49 UTC, sergiorg-hpc commented on bluebrain/repo-bluebrain/packages/coreneuron/package.py
>      version('1.0.0.20220304', commit='2d08705')
@pramodk At some point, we should probably consider removing most of the temporary versions but one (e.g., latest). I find it silly that we still have these around, haha :P

2022-08-30 08:01 UTC, pramodk commented on bluebrain/repo-bluebrain/packages/coreneuron/package.py
>      version('1.0.0.20220304', commit='2d08705')
don't hesitate to remove those right away!

2022-08-30 08:47 UTC, olupton commented
Can you also rebase? I still see `coreneuron@develop` in the logs: https://bbpgitlab.epfl.ch/hpc/spack/-/jobs/340699#L1674

2022-08-30 08:48 UTC, olupton commented on bluebrain/repo-bluebrain/packages/coreneuron/package.py
> +    conflicts('+shared', when='@:8.9.9 +gpu')
This seems fine to me, this support will not be backported to the 8.2 series and probably not to any hypothetical 8.3 series either.

2022-08-30 09:19 UTC, matz-e commented on bluebrain/repo-bluebrain/packages/coreneuron/package.py
> +    conflicts('+shared', when='@:8.9.9 +gpu')
```suggestion
    conflicts('+shared', when='@:8 +gpu')
```
More concise.

2022-08-30 11:12 UTC, olupton commented
https://bbpgitlab.epfl.ch/hpc/spack/-/jobs/341052#L1673 looks better, no more @develop.

2022-08-30 11:12 UTC, olupton approved these changes

2022-08-30 12:24 UTC, merged