Add dependency to intel-oneapi-mkl when using intel-oneapi-compilers
BlueBrain/spack pull request #1680
Opened 2022-08-30 09:29 UTC by sergiorg-hpc

2022-08-30 09:30 UTC, matz-e requested changes
Should be a separate module.

2022-08-31 11:28 UTC, kotsaloscv approved these changes

2022-08-31 11:39 UTC, sergiorg-hpc commented
@matz-e, should we merge? Your call!

2022-08-31 12:09 UTC, matz-e approved these changes

2022-08-31 12:58 UTC, merged