Update to Spack 0.19
BlueBrain/spack pull request #1765
Opened 2022-11-15 10:45 UTC by heerener

2022-11-15 16:06 UTC, matz-e requested changes
Fix the build failures, please.

2022-11-23 08:58 UTC, matz-e commented on bluebrain/repo-patches/packages/py-opencv-python/package.py
> -    homepage = "https://pypi.org/project/opencv-python"
Homepage should still be there :)

2022-12-16 10:02 UTC, matz-e requested changes

2022-12-16 10:02 UTC, matz-e commented on bluebrain/deployment/environments/externals.yaml
> +    - julia@1.6
```suggestion
    - julia@1.6  # As requested by Polina S.
```

2023-02-21 12:48 UTC, pramodk commented
@matz-e : about the a488d7cbdd1d3e78c997f5b759acc727aafa22ee - we will need hpctoolk one way or another. So soon we will need to find a solution to this.

2023-03-02 16:02 UTC, merged