neuron: deploy new version with NVHPC fixes
BlueBrain/spack pull request #1847
Opened 2023-02-24 15:57 UTC by iomaganaris

- Fixes issues with NEURON when +shared+gpu (with OpenACC) are enabled
- Related to failures in https://bbpgitlab.epfl.ch/hpc/spack/-/pipelines/104359

2023-02-24 16:03 UTC, olupton requested changes

2023-02-24 16:03 UTC, olupton commented on bluebrain/repo-patches/packages/neuron/package.py
> +    version("9.0.a5", commit="bea7eb8")
Just to flag this should not be merged as-is because this commit is not on master.

2023-03-07 15:19 UTC, olupton submitted a review, later dismissed

2023-03-07 15:26 UTC, olupton commented
We may actually want to merge https://github.com/neuronsimulator/nrn/pull/2252 and bump past that one too.

2023-03-07 16:08 UTC, olupton commented on bluebrain/repo-patches/packages/neuron/package.py
> +    version("9.0.a5", commit="bccc357")
Going to be updated again with https://github.com/neuronsimulator/nrn/pull/2252.

2023-03-08 14:59 UTC, olupton approved these changes

2023-03-08 15:15 UTC, alexsavulescu approved these changes

2023-03-08 15:22 UTC, merged