py-bluecellulab: add package
BlueBrain/spack pull request #2149
Opened 2023-10-11 11:15 UTC by arnaudon

2023-10-11 12:21 UTC, anilbey requested changes
There are these 3 new dependencies.

```
        "bluepysnap>=1.0.5,<2.0.0",
        "pydantic>=1.10.2,<2.0.0",
        "typing-extensions>=4.8.0"
```

and the py-cachetools as well as bluepy-configfile can be removed safely

2023-10-11 12:21 UTC, anilbey commented on bluebrain/repo-bluebrain/packages/py-bluecellulab/package.py
> +    depends_on("py-cachetools", type=("build", "run"))
This dependency has been removed. You can remove it here also.

2023-10-11 12:36 UTC, arnaudon commented on bluebrain/repo-bluebrain/packages/py-bluecellulab/package.py
> +    depends_on("py-cachetools", type=("build", "run"))
done!

2023-10-11 12:45 UTC, anilbey approved these changes, later dismissed
Looks very good to me, thanks!

2023-10-11 13:02 UTC, matz-e reviewed
While we're at it, why not stop deploying `bglibpy`? I'll probably have to patch up the module tests, though.

2023-10-11 13:02 UTC, matz-e commented on bluebrain/deployment/environments/applications_science.yaml
>      - py-bglibpy
```suggestion
```

2023-10-11 13:02 UTC, matz-e commented on bluebrain/deployment/environments/applications_science.yaml
>            - py-bglibpy
```suggestion
```

2023-10-12 09:21 UTC, matz-e commented
@arnaudon we have this test for `bglibpy` that I tried to "massage" into a hybrid that would work with `bluecellulab`:

https://bbpgitlab.epfl.ch/hpc/module-testing/-/blob/main/scripts/bglibpy_test.py?ref_type=heads

Would you be able to help me fix that error from the module testing?
```
Mod lib:  No mechanisms are loaded.
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/ssd/gitlab_map_jobs/bbpcihpcproj12/J955664/hpc/module-testing/scripts/bglibpy_test.py", line 8, in <module>
    soma.insert('Ca_HVA2')
ValueError: argument not a density mechanism name.
```

Full test script:
```python
try:
    import bglibpy
    neuron = bglibpy.neuron
except:
    import bluecellulab
    neuron = bluecellulab.neuron
soma = neuron.h.Section()
soma.insert('Ca_HVA2')
neuron.h.load_file('stdrun.hoc')
neuron.h.run()
print(soma.v)
vecstim = neuron.h.VecStim()
```

2023-10-12 09:29 UTC, anilbey commented
Hi @matz-e how are you loading the mechanisms before loading the script? Are you using the `BGLIBPY_MOD_LIBRARY_PATH` environment variable or is NEURON loading the mechanisms in your cwd at the time you write the import statement?

2023-10-12 09:42 UTC, anilbey commented
I could run your script with the compiled mod files are provided.

```
❯ python spack-test.py
        1 
Imported NEURON from: /VENV_PATH/bluecellulab311/lib/python3.11/site-packages/neuron/__init__.py
Mod lib:  /MOD_PATH/BlueCelluLab/x86_64
-64.99999985986676

```

The way of loading mechanisms is changed in bluecellulab. It is now relying on NEURON's API for doing so. 

It is described in here: https://bluecellulab.readthedocs.io/en/latest/compiling-mechanisms.html

2023-10-12 14:03 UTC, matz-e approved these changes

2023-10-12 14:04 UTC, merged

2023-10-13 06:45 UTC, arnaudon commented
Thank you for you help on that one!