caliper: pin version to 2.8.0 due to segfault issue with the 2.10.0
BlueBrain/spack pull request #2294
Opened 2024-02-05 20:11 UTC by pramodk

I will report the issue upstream. For now, lets use the older version that was working OK.

2024-02-05 20:42 UTC, pramodk commented on bluebrain/deployment/environments/applications_libraries.yaml
> +    - caliper+cuda@2.8.0 cuda_arch=70
@matz-e : This is not sufficient to enforce 2.8.0 as preferred. What is the current way to set the preferred version? 
* I guess we no longer have packages.yaml
* Should I update the recipe in the builtin repo directly? Or, just create one in repo-patches?

2024-02-06 08:22 UTC, pramodk commented
Multiscale-Run module check is failing but that's irrelevant for this PR.

2024-02-06 08:36 UTC, matz-e requested changes
No. This goes under the `packages:caliper:require:@2.91` setting in `bluebrain/sysconfig/bluebrain5/packages.yaml`.

2024-02-06 10:14 UTC, matz-e submitted a review, later dismissed

2024-02-06 10:14 UTC, matz-e commented on bluebrain/sysconfig/bluebrain5/packages.yaml
> +    version: [2.9.1]
```suggestion
    require: "@2.9.1"
```
for a "hard" requirement

2024-02-06 10:26 UTC, matz-e approved these changes

2024-02-06 10:47 UTC, merged