bba-data-push: Release 3.0.0
BlueBrain/spack pull request #2309
Opened 2024-02-14 08:58 UTC by eleftherioszisis

2024-02-14 09:35 UTC, lecriste commented on bluebrain/repo-bluebrain/packages/py-bba-data-push/package.py
v3.0.0 requires also
`depends_on("py-voxcell", type=("build", "run"))`

2024-02-14 10:07 UTC, lecriste approved these changes, later dismissed
I wonder what [this](https://github.com/BlueBrain/spack/pull/2309#issuecomment-1943400694) means.

2024-02-14 10:12 UTC, matz-e requested changes
@eleftherioszisis needs a version restriction on `py-nexusforge`, with a new version added into that latter package.

2024-02-14 10:50 UTC, lecriste submitted a review, later dismissed
@matz-e, by adding 
`depends_on("py-nexusforge@0.8.1", type=("build", "run"), when="@3.0.0:")`
what happens to the `py-nexusforge` version of v1.0.8 if we don't add
`depends_on("py-nexusforge@0.8.0", type=("build", "run"), when="@1.0.8")`
?

2024-02-15 13:34 UTC, eleftherioszisis commented
I updated py-bbp-workflow and py-cwl-registry to play nicely with py-bba-data-push 3.0.0.

2024-02-15 13:54 UTC, matz-e approved these changes

2024-02-15 13:55 UTC, matz-e commented
> @matz-e, by adding `depends_on("py-nexusforge@0.8.1", type=("build", "run"), when="@3.0.0:")` what happens to the `py-nexusforge` version of v1.0.8 if we don't add `depends_on("py-nexusforge@0.8.0", type=("build", "run"), when="@1.0.8")` ?

If you don't add the second line (or a generic dependency on `py-nexusforge`), Spack will not see any dependency on nexus forge at all.

2024-02-15 15:39 UTC, merged