py-connectome-manipulator: Release 0.0.10
BlueBrain/spack pull request #2456
Opened 2024-06-11 12:12 UTC by eleftherioszisis

2024-06-11 13:37 UTC, matz-e requested changes
The version constraints on some of the dependencies can now be dropped; `py-submitit` altogether, too!

2024-06-11 13:48 UTC, eleftherioszisis commented
@matz-e better?

2024-06-11 13:56 UTC, matz-e commented on bluebrain/repo-bluebrain/packages/py-connectome-manipulator/package.py
>      depends_on("py-dask-mpi", type=("build", "run"), when="@0.0.6:")
```suggestion
    depends_on("py-distributed", type=("build", "run"))
    depends_on("py-dask-mpi", type=("build", "run"))
```

2024-06-11 14:34 UTC, matz-e approved these changes

2024-06-11 16:17 UTC, eleftherioszisis commented
Not sure why matplotlib is not found given that it is a dependency in py-neurom.

2024-06-12 07:21 UTC, matz-e commented
Purged PR directory, rebuilding from scratch.

The spec JSON files on disk had the right dependencies set up. Not sure why that one module did not contain matplotlib. Let's see.

2024-06-12 08:02 UTC, merged