adding Brayns' plugin membraneless organelles
BlueBrain/spack pull request #416
Opened 2019-06-25 08:31 UTC by ppodhajski

2019-06-25 11:56 UTC, pramodk reviewed
Quick comments: 

- I wouldn't depend on develop for re-producibility.
- instead of commit, I would suggest to use tags/releases

2019-06-25 11:59 UTC, matz-e requested changes

2019-06-25 11:59 UTC, matz-e commented on var/spack/repos/builtin/packages/brayns-topologyviewer/package.py
> +    version('0.1.0', commit='58a61253c1e33aea7248c7894398035a36608674', submodules=True,  preferred=True)
```suggestion
    version('0.1.0', commit='58a61253c1e33aea7248c7894398035a36608674', submodules=True)
```

2019-08-29 07:14 UTC, ppodhajski commented
retest this please

2019-09-02 08:58 UTC, matz-e approved these changes

2019-09-02 08:59 UTC, matz-e requested changes
Overlooked this

2019-09-02 08:59 UTC, matz-e commented on var/spack/repos/builtin/packages/brayns-brainatlas/package.py
> +    version('0.1.0', tag='v0.1.0', preferred=True)
```suggestion
    version('0.1.0', tag='v0.1.0')
```

2019-09-02 08:59 UTC, matz-e commented on var/spack/repos/builtin/packages/brayns-topologyviewer/package.py
> +    version('0.1.0', tag='v0.1.0', submodules=True, preferred=True)
```suggestion
    version('0.1.0', tag='v0.1.0', submodules=True)
```

2019-09-02 11:25 UTC, matz-e approved these changes

2019-09-02 12:58 UTC, merged