Add BBP test data
BlueBrain/spack pull request #427
Opened 2019-07-01 14:53 UTC by ppodhajski

2019-07-02 15:34 UTC, pramodk commented on var/spack/repos/builtin/packages/bbptestdata/package.py
> +    version('2.0.0')
do we have tag for this?

2019-07-02 15:34 UTC, pramodk commented on var/spack/repos/builtin/packages/bbptestdata/package.py
> +            make('install')
Isn't this default for CMake project? (i.e. this can be removed)

2019-07-02 15:34 UTC, pramodk commented on var/spack/repos/builtin/packages/brayns/package.py
> +    depends_on('bbptestdata')
can we make variant like `test` for this dependency? Idea is people should be able to build brayns even if they don't have access to bbptestdata (which is only internal).

2019-07-03 16:30 UTC, matz-e requested changes
https://spack.readthedocs.io/en/latest/packaging_guide.html#depends-on

That page mentions something about a dependency type `test`. We should really use that if possible.

2019-07-03 16:30 UTC, matz-e commented on var/spack/repos/builtin/packages/brayns/package.py
> +    variant('test_data', default=False, description='Run extra tests with BBPTestData')
```suggestion
```

2019-07-03 16:30 UTC, matz-e commented on var/spack/repos/builtin/packages/brayns/package.py
> +    depends_on('bbptestdata', when ='+test_data')
```suggestion
    depends_on('bbptestdata', type='test')
```

2019-07-05 06:57 UTC, matz-e approved these changes

2019-07-05 07:02 UTC, merged