add ultraliser package
BlueBrain/spack pull request #529
Opened 2019-09-27 09:59 UTC by ppodhajski

2019-09-27 12:33 UTC, matz-e approved these changes
Shouldn't it be "Ultralizer"?

2019-09-27 13:29 UTC, ppodhajski commented
> Shouldn't it be "Ultralizer"?
Good question for @marwan-abdellah  ;-)

should it be in gnu-stable-serial? it does not require python and I guess there is some additional check now as it fails:

`12:13:59  ==> Error: ultraliser does not depend on python`

2019-09-27 13:56 UTC, matz-e requested changes

2019-09-27 13:56 UTC, matz-e commented on deploy/packages/bbp-packages.yaml
> +      - ultraliser
Your intuition is right. This should actually be in `gnu-stable` if it does not depend on Python. See the very bottom of this file.

2019-09-30 06:48 UTC, matz-e approved these changes

2019-09-30 06:48 UTC, matz-e commented
Let's nix nix!

2019-09-30 09:42 UTC, merged