touchdetector: add a depends to highfive
BlueBrain/spack pull request #546
Opened 2019-10-10 07:01 UTC by alkino

2019-10-10 08:07 UTC, matz-e requested changes

2019-10-10 08:07 UTC, matz-e commented on var/spack/repos/builtin/packages/touchdetector/package.py
> +    depends_on('highfive@develop', when='@5.3.0:')
Why do we need `@develop`?

2019-10-10 08:07 UTC, matz-e commented on var/spack/repos/builtin/packages/touchdetector/package.py
> +    depends_on('highfive@develop', when='@5.3.0:')
Can we depend on just `HighFive`?

2019-10-10 08:08 UTC, alkino commented on var/spack/repos/builtin/packages/touchdetector/package.py
> +    depends_on('highfive@develop', when='@5.3.0:')
Too much modifications since the last version

2019-10-10 08:08 UTC, alkino commented on var/spack/repos/builtin/packages/touchdetector/package.py
> +    depends_on('highfive@develop', when='@5.3.0:')
i will try to reduce dependency

2019-10-14 09:14 UTC, alkino commented on var/spack/repos/builtin/packages/touchdetector/package.py
> +    depends_on('highfive@develop', when='@5.3.0:')
done

2019-10-14 09:15 UTC, matz-e approved these changes

2019-10-14 12:11 UTC, matz-e approved these changes

2019-10-14 14:08 UTC, merged