py-basalt: add 0.2.8 / remove others
BlueBrain/spack pull request #603
Opened 2019-11-22 14:15 UTC by tristan0x

Fixes #103

2019-11-22 14:18 UTC, jorblancoa approved these changes

2019-11-22 17:36 UTC, matz-e requested changes

2019-11-22 17:36 UTC, matz-e commented on var/spack/repos/builtin/packages/py-basalt/package.py
> +    version('0.2.8', git=url, tag='v0.2.8', submodules=True, preferred=True, clean=False)
```suggestion
    version('0.2.8', git=url, tag='v0.2.8', submodules=True, clean=False)
```

2019-11-26 09:51 UTC, matz-e approved these changes

2019-12-02 12:42 UTC, tristan0x commented
retest this please Jenkins

2020-02-10 07:41 UTC, matz-e commented
Retest this please

2020-02-19 15:54 UTC, closed without merging