Brion sonata
BlueBrain/spack pull request #651
Opened 2020-01-08 09:36 UTC by NadirRoGue

2020-01-08 12:18 UTC, ppodhajski commented
retest this please

2020-01-08 12:39 UTC, matz-e reviewed
It quit with `package blender not found`. Are you on the latest spack? Seems like maybe a rebase is in order…

2020-01-08 12:39 UTC, matz-e commented on var/spack/repos/builtin/packages/brion/package.py
> +    depends_on('libsonata', when='@3.1.0')
```suggestion
    depends_on('libsonata', when='@3.1.0:')
```
I assume this dependency will stay in the future. Then we should use an open range (:

2020-01-08 12:39 UTC, matz-e commented on var/spack/repos/builtin/packages/brion/package.py
> +        if '+libsonata' in self.spec:
What is this supposed to do? Since you have no `libsonata` variant, it shouldn't get triggered.

2020-01-08 12:40 UTC, matz-e commented
Please update the PR description to something like `brion: add sonata support` or similiar. Just `Brion sonata` is not all that meaningful when looking at commit logs.

2020-01-09 08:47 UTC, ppodhajski commented
retest this please

2020-01-09 10:49 UTC, tristan0x reviewed
If you want to bump the brion module deployed on BB5 to 3.1.0, you have to update `packages/bbp-packages.yaml` as well. Also I guess 3.1.0 should be the one _prefered_.

2020-01-09 15:14 UTC, pramodk requested changes
and this is what Tristan pointed:

```
→ grep -r brion deploy/*
deploy/packages/bbp-packages.yaml:      - brion@3.0.0 +python ^boost@1.65.0
```

2020-01-09 15:14 UTC, pramodk commented on var/spack/repos/builtin/packages/brion/package.py
> +        if self.version >= Version('3.1.0'):
```suggestion
        if self.spec.satisfies('@3.1.0:'):
```

2020-01-10 15:11 UTC, pramodk approved these changes

2020-01-13 11:16 UTC, merged

2020-01-13 23:02 UTC, matz-e commented
> If you want to bump the brion module deployed on BB5 to 3.1.0, you have to update `packages/bbp-packages.yaml` as well. Also I guess 3.1.0 should be the one _prefered_.

The newest version is always preferred.