add new package aibs-circuit-converter
BlueBrain/spack pull request #703
Opened 2020-02-18 14:46 UTC by asanin-epfl

Hi! Please review.

2020-02-20 09:42 UTC, matz-e commented on var/spack/repos/builtin/packages/py-aibs-circuit-converter/package.py
> +    version('develop', branch='master')
Can we add a version/tag here, please?

2020-02-20 12:13 UTC, matz-e requested changes

2020-02-20 12:13 UTC, matz-e commented on var/spack/repos/builtin/packages/py-aibs-circuit-converter/package.py
> +# Copyright 2013-2018 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
```

2020-02-20 13:26 UTC, asanin-epfl commented
@matz-e Should I update License date in https://github.com/BlueBrain/spack/blob/develop/var/spack/repos/builtin/packages/py-neuron-reduce/package.py#L1 ? I've merged it already unfortunately.

2020-02-21 12:00 UTC, asanin-epfl commented on var/spack/repos/builtin/packages/py-aibs-circuit-converter/package.py
> +    version('develop', branch='master')
done

2020-02-24 10:12 UTC, matz-e approved these changes

2020-02-24 10:12 UTC, matz-e commented on var/spack/repos/builtin/packages/py-aibs-circuit-converter/package.py
> +# Copyright 2013-2018 Lawrence Livermore National Security, LLC and other
I don't see the change?

2020-02-24 11:03 UTC, merged