Add py-quaternion
BlueBrain/spack pull request #721
Opened 2020-02-26 12:04 UTC by wizmer

2020-02-26 13:06 UTC, matz-e requested changes

2020-02-26 13:06 UTC, matz-e commented on var/spack/repos/builtin/packages/py-pyquaternion/package.py
> +    url      = "https://files.pythonhosted.org/packages/ae/c8/02b30c4a86744d2e15f7f16ab353f7231bd0241117713e5d60f466044994/pyquaternion-0.9.5.tar.gz"
NO!
```suggestion
    url      = "https://pypi.org/packages/source/p/pyquaternion/pyquaternion-0.9.5.tar.gz"
```

2020-02-26 13:07 UTC, matz-e requested changes

2020-02-26 13:07 UTC, matz-e commented on var/spack/repos/builtin/packages/py-pyquaternion/package.py
> +# Copyright 2020 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
```

2020-02-26 14:01 UTC, matz-e requested changes

2020-02-26 14:01 UTC, matz-e commented on var/spack/repos/builtin/packages/py-plotly-helper/package.py
> +# Copyright 2020 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
```

2020-02-26 15:29 UTC, wizmer commented
@matz-e Can we merge this first part please

2020-02-27 05:23 UTC, pramodk approved these changes
LGTM

2020-02-27 07:09 UTC, matz-e approved these changes

2020-02-27 08:46 UTC, merged

2020-02-28 08:35 UTC, mgeplf commented on var/spack/repos/builtin/packages/py-cut-plane/package.py
> +    """Python morphology manipulation toolkit"""
c&p from py-morph-tool?