Upstream updates for py-jupyter-core and py-jupyter-client
BlueBrain/spack pull request #728
Opened 2020-02-27 18:18 UTC by pramodk

Updated required for issues mentioned in https://github.com/jupyter/jupyter/issues/334

2020-02-28 08:00 UTC, matz-e requested changes

2020-02-28 08:00 UTC, matz-e commented on var/spack/repos/builtin/packages/py-jupyter-client/package.py
> -
Why? :pineapple:

Two newlines before class definitions…

2020-03-06 10:23 UTC, jorblancoa commented on var/spack/repos/builtin/packages/py-jupyter-client/package.py
> -
you are right!
`var/spack/repos/builtin/packages/py-jupyter-client/package.py:8: [E302] expected 2 blank lines, found 1`

2020-03-06 21:17 UTC, pramodk commented on var/spack/repos/builtin/packages/py-jupyter-client/package.py
> -
I didn't notice that because I just checkout this package from upstream!

2020-05-04 08:23 UTC, matz-e commented
@pramodk, @jorblancoa  updates here?

2020-05-04 08:30 UTC, jorblancoa commented
This can be closed, was added to this PR https://github.com/BlueBrain/spack/pull/545/files

2020-05-04 08:30 UTC, closed without merging