Setup common models before building any model
BlueBrain/spack pull request #734
Opened 2020-03-02 22:25 UTC by pramodk

@ferdonline : See analysis in https://bbpteam.epfl.ch/project/issues/browse/CNEUR-343
If there is better way to fix this, please go ahead.

2020-03-03 08:05 UTC, matz-e approved these changes
LGTM from the Spack side.

2020-03-03 08:06 UTC, matz-e requested changes
Missed the flake8 bits, though.

2020-03-03 08:06 UTC, matz-e commented on var/spack/repos/builtin/packages/neurodamus-model/package.py
```suggestion
```

2020-03-03 08:06 UTC, matz-e commented on var/spack/repos/builtin/packages/neurodamus-model/package.py
> +    phases = ['setup_common_mods', 'build_model', 'merge_hoc_mod', 'build', 'install']
```suggestion
    phases = [
        'setup_common_mods', 'build_model', 'merge_hoc_mod', 'build', 'install'
    ]
```

2020-03-03 09:34 UTC, matz-e submitted a review, later dismissed

2020-03-03 10:18 UTC, ferdonline submitted a review, later dismissed
That makes all the sense! The fix looks good to me!

2020-03-09 19:25 UTC, pramodk commented
Please retest

2020-04-01 07:22 UTC, pramodk commented
please retest

2020-05-14 08:55 UTC, matz-e approved these changes

2020-06-09 20:21 UTC, pramodk commented
@ferdonline @iomaganaris @jorblancoa  : I am merging this long pending change! So if something breaks, you know where to look at :)

2020-06-09 20:21 UTC, merged