py-sonata-network-reduction0.0.6
BlueBrain/spack pull request #759
Opened 2020-03-28 10:58 UTC by asanin-epfl

All necessary changes for the version with lower dependencies.

I checked. It worked on BB5.
```
-bash-4.2$ . spack/share/spack/setup-env.sh
-bash-4.2$ export SPACK_INSTALL_PREFIX=${HOME}/software
-bash-4.2$ spack install --no-cache py-sonata-network-reduction
....
==> Installing py-sonata-network-reduction
==> Cloning git repository: ssh://bbpcode.epfl.ch/nse/sonata-network-reduction at tag sonata-network-reduction-v0.0.6.dev0
Total 111 (delta 14), reused 76 (delta 14)
Total 435 (delta 182), reused 435 (delta 182)
Fetching tags only, you probably meant:
  git fetch --tags
==> No checksum needed when fetching with git
==> Already staged spack-stage-py-sonata-network-reduction-0.0.6-4kv2vrx5eum2dwglaynpxjvrke2pxspw in /tmp/sanin/spack-stage-py-sonata-network-reduction-0.0.6-4kv2vrx5eum2dwglaynpxjvrke2pxspw
==> No patches needed for py-sonata-network-reduction
==> Building py-sonata-network-reduction [PythonPackage]
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed py-sonata-network-reduction
  Fetch: 2.91s.  Build: 8.15s.  Total: 11.06s.
[+] /gpfs/bbp.cscs.ch/home/sanin/software/install/linux-rhel7-x86_64/gcc-8.3.0/py-sonata-network-reduction-0.0.6-4kv2vr
-bash-4.2$ module load unstable
-bash-4.2$ spack module tcl refresh py-sonata-network-reduction@0.0.6 
==> You are about to regenerate tcl module files for:

-- linux-rhel7-x86_64 / gcc@8.3.0 -------------------------------
4kv2vrx py-sonata-network-reduction@0.0.6

==> Do you want to proceed? [y/n] y
==> Regenerating tcl module files
-bash-4.2$ module load py-sonata-network-reduction
Autoloading python/3.7.4
Autoloading py-efel/3.0.70
Autoloading py-bluepyopt/1.9.12
py-bluepyopt(37):ERROR:105: Unable to locate a modulefile for 'py-bluepyopt/1.9.12'
Autoloading py-bluepy/0.14.6
Autoloading brion/3.1.0
Autoloading py-bglibpy/4.2.14
Autoloading hpe-mpi/2.21
-bash-4.2$ module load neurodamus-hippocampus/0.4
Autoloading reportinglib/2.5.3
-bash-4.2$ cd /gpfs/bbp.cscs.ch/project/proj30/home/sanin/CA1.O0/
-bash-4.2$ sonata-network-reduction node 0 sonata-reduced-node All sonata/circuit_config.json 
loading template 'model'
loading default reduced model
There is no segment to segment copy, it means that some segments in the reduced model did not receive channels from the original cell
trying to compensate by copying channels from neighboring segments

Warning: section 1 is the only child of section: 0
It will be merged with the parent section
-bash-4.2$
```

2020-03-30 06:56 UTC, matz-e submitted a review, later dismissed

2020-03-30 07:39 UTC, pramodk requested changes
Would like to wait to check these constraints on Piz-Daint before merge.

2020-03-30 10:34 UTC, jorblancoa commented
Tested and validated on Piz-Daint!

2020-04-01 07:18 UTC, pramodk commented
@jorblancoa : If this is incorporated into #545, can you close?

2020-04-03 13:43 UTC, jorblancoa commented
> @jorblancoa : If this is incorporated into #545, can you close?

The only difference is that py-pandas version is back to 0.25: in py-sonata-network-reduction but i will update #545 and we can close this.

2020-04-20 11:58 UTC, closed without merging