Add git to list of deployed modules
BlueBrain/spack pull request #767
Opened 2020-04-07 09:27 UTC by wizmer

2020-04-07 10:13 UTC, matz-e requested changes
Should be moved into the `tools` config, that's where it's deployed, too.

2020-04-07 10:13 UTC, matz-e commented on deploy/configs/applications/modules.yaml
> +      - git
This does not go here, since we don't develop git.

2020-04-07 10:40 UTC, pramodk commented
I am sure the answer is no but just to ask - I assume we are not using any new git features that Spack will need while cloning repo? (e.g. for sibmodules).

2020-04-07 13:42 UTC, wizmer commented
Just to try to understand the point of your question. The module would not be loaded except if explicitly required, no ? How can this affect the Spack workflow ?

2020-04-08 08:59 UTC, matz-e commented
> I am sure the answer is no but just to ask - I assume we are not using any new git features that Spack will need while cloning repo? (e.g. for sibmodules).

I'm not sure why a newer git is essential (although I have a private module), but I think things like `--force-with-lease` are not in the stock version. @wizmer is that the feature you desire?

2020-04-08 09:11 UTC, wizmer commented
Yes, --force-with-lease and also the new way of managing branches. It seems to me a bit faster as well.

2020-04-08 09:46 UTC, matz-e commented
@pramodk while we want to minimize the modules present, I think this is a scenario where it would make sense to enable `git`. After all, our own team has endorsed functionality present only in newer `git`s…

2020-04-08 09:46 UTC, matz-e commented
To add, contrary to `emacs` :angry:, this would probably be a wider used module

2020-04-30 08:12 UTC, matz-e submitted a review, later dismissed

2020-04-30 08:46 UTC, matz-e approved these changes

2020-04-30 08:47 UTC, merged