brainbuilder@0.12.0
BlueBrain/spack pull request #839
Opened 2020-06-10 16:03 UTC by asanin-epfl

I need help here with py-pandas@1.0.3. It does not compile.

@wizmer I'm just going to put it here https://github.com/BlueBrain/morph-tool/pull/13#discussion_r425001873

2020-06-10 19:07 UTC, matz-e commented on var/spack/repos/builtin/packages/py-pandas/package.py
> +    version('1.0.3', sha256='32f42e322fb903d0e189a4c10b75ba70d90958cc4f66a1781ed027f1a1d14586')
What feature is needed from this?

2020-06-10 19:07 UTC, matz-e commented on var/spack/repos/builtin/packages/brainbuilder/package.py
> +    depends_on('py-morph-tool@0.2.3:', type='run', when='@0.11.9:')
```
py-morph-tool requires py-neurom version 1.4.15:, but spec asked for mut_morphio
```
Something is messed up.

2020-06-11 07:13 UTC, wizmer commented on var/spack/repos/builtin/packages/py-pandas/package.py
> +    version('1.0.3', sha256='32f42e322fb903d0e189a4c10b75ba70d90958cc4f66a1781ed027f1a1d14586')
It's not a feature but users are encouraged to move away from 0.25 as it was a transitional version. 0.25 and 1.0.3 are not fully compatible either. Also pandas 1.+ is the first Pandas that can be considered as stable.

2020-06-11 07:35 UTC, matz-e commented on var/spack/repos/builtin/packages/py-pandas/package.py
> +    version('1.0.3', sha256='32f42e322fb903d0e189a4c10b75ba70d90958cc4f66a1781ed027f1a1d14586')
In that case, I'd rather consider backporting (i.e. copying over) the package from upstream Spack. I was just wondering if there's a hard reason to switch.

We're also due for a deployment update soon™, that would probably bring an update to Pandas anyways. If you want it now and copy the official package over, then that will make merging upstream easier.

2020-06-11 07:37 UTC, wizmer commented on var/spack/repos/builtin/packages/py-pandas/package.py
> +    version('1.0.3', sha256='32f42e322fb903d0e189a4c10b75ba70d90958cc4f66a1781ed027f1a1d14586')
Yes, that was my original idea as well. I will take care of it.

2020-06-11 07:38 UTC, matz-e commented on var/spack/repos/builtin/packages/brainbuilder/package.py
> +    depends_on('py-morph-tool@0.2.3:', type='run', when='@0.11.9:')
See the last item of the [FAQ](https://github.com/BlueBrain/spack/blob/develop/FAQ.md). If you don't do the `spacktivate`, but use your local Spack with the branch on the pull request, you can roll back the dependencies one by one and see when it breaks.

2020-06-11 08:36 UTC, tomdele commented
Pandas 1.0.3 is python 3 only. 
I though we wanted to keep brainbuilder python2 compatible for a while ?

2020-06-11 08:37 UTC, matz-e commented
> Pandas 1.0.3 is python 3 only.
> I though we wanted to keep brainbuilder python2 compatible for a while ?

Our deployment is Python3 only already. Note that this does not impede your ability to lower the requirements in `setup.py` or on PyPI.

2020-06-11 09:07 UTC, tomdele commented
@matz-e  Yes indeed... I got confused.

2020-06-11 10:00 UTC, matz-e requested changes
`py-plotly-helper` contains this:/
```
depends_on('py-neurom@mut_morphio+plotly', type='run')
```
which breaks here. Is that `@mut_morphio` really necessary for a *helper*?

2020-06-11 11:49 UTC, asanin-epfl commented
@wizmer can you please clarify on `py-plotly-helper` and its dependency to `py-neurom@mut_morphio+plotly`?

2020-06-11 12:40 UTC, matz-e commented
> @wizmer can you please clarify on `py-plotly-helper` and its dependency to `py-neurom@mut_morphio+plotly`?
> Should we update dependency in `py-morph-tool/package.py` to `depends_on('py-neurom@1.4.15:+mut_morphio', type='run', when='@0.1.14:')` ?

There's no `+mut_morphio`, it's a version, so `@mut_morphio`. Really I would not expect a `plotly` helper to be so version dependent.

2020-06-11 12:47 UTC, wizmer commented
Plotly-helper does not require @mut_morphio so it can be removed if needed.

2020-06-11 12:54 UTC, asanin-epfl commented
ok, I will remove it

2020-06-11 16:26 UTC, asanin-epfl commented
Finally Test Build passed

2020-06-12 08:36 UTC, asanin-epfl commented
Should I retest this? travis is hanged for some reason

2020-06-12 08:58 UTC, matz-e commented
> Should I retest this? travis is hanged for some reason

Grr… Travis seems a little sketchy over the last ~week. I'll have a look. In the web interface, it actually failed. Just retriggered Travis…

2020-06-12 08:59 UTC, matz-e submitted a review, later dismissed
Thanks, looks good now. Just need to satisfy Travis…

2020-06-12 09:48 UTC, asanin-epfl commented
Hooray!

2020-06-12 09:58 UTC, tomdele approved these changes

2020-06-12 10:07 UTC, merged