Add bluepyefe and igor packages
BlueBrain/spack pull request #874
Opened 2020-07-21 14:52 UTC by DrTaDa

2020-07-21 19:43 UTC, matz-e commented on var/spack/repos/builtin/packages/py-bluepyefe/package.py
> +    version('0.3.13', commit='163ee6e48c4091c0a2347800d85c61d357cf26b4')
Tags would be preferred :)

2020-07-22 07:27 UTC, matz-e requested changes

2020-07-22 07:27 UTC, matz-e commented on var/spack/repos/builtin/packages/py-bluepyefe/package.py
> +
```suggestion

```

2020-07-22 07:27 UTC, matz-e commented on var/spack/repos/builtin/packages/py-bluepyefe/package.py
> +
```suggestion
```

2020-07-22 07:27 UTC, matz-e commented on var/spack/repos/builtin/packages/py-igor/package.py
> +
```suggestion
```

2020-07-22 07:28 UTC, matz-e commented
Emacs should have some configuration options to purge spurious whitespace…

2020-07-22 08:27 UTC, matz-e requested changes

2020-07-22 08:27 UTC, matz-e commented on var/spack/repos/builtin/packages/py-bluepyefe/package.py
> +    url = "https://pypi.io/packages/source/b/bluepyefe/bluepyefe-0.3.13.tar.gz"
```suggestion
    url = "https://pypi.io/packages/source/b/bluepyefe/bluepyefe-0.3.13.tar.gz"

```
Sorry, there should still be a newline.

2020-07-22 08:27 UTC, matz-e commented on var/spack/repos/builtin/packages/py-igor/package.py
> +    version('0.3', url=url)
Please use `sha256` here for the checksum of the tarball.

2020-07-22 08:39 UTC, DrTaDa commented on var/spack/repos/builtin/packages/py-bluepyefe/package.py
> +    version('0.3.13', commit='163ee6e48c4091c0a2347800d85c61d357cf26b4')
What are tags ?

2020-07-22 09:10 UTC, DrTaDa commented
It seems there is an error with the setuptools for py-igor:
`error: option --single-version-externally-managed not recognized`

Did I make a mistake by specifying https://github.com/BlueBrain/spack/blob/9895229d316720eb374150aa89a1ba025b1c37ea/var/spack/repos/builtin/packages/py-igor/package.py#L17 ?

2020-07-23 12:55 UTC, matz-e requested changes

2020-07-23 12:55 UTC, matz-e commented on var/spack/repos/builtin/packages/py-igor/package.py
> +
```suggestion

    def patch(self):
        setupfile = FileFilter('setup.py')
        setupfile.filter('distutils.core', 'setuptools')

```

This is necromancy, that package seems so old… try this modification to use some *modern* Python stuff, maybe it'll help

2020-07-23 12:55 UTC, matz-e commented on var/spack/repos/builtin/packages/py-igor/package.py
> +
Ideally, this would actually be below the block of `depends_on`…

2020-07-24 11:15 UTC, matz-e approved these changes

2020-07-27 19:31 UTC, pramodk commented
@DrTaDa : can be merged?

2020-07-28 07:43 UTC, DrTaDa commented
> @DrTaDa : can be merged?

@pramodk Yes! Thank you

2020-07-28 08:39 UTC, merged

2020-07-28 08:46 UTC, wvangeit commented
@pramodk can you also include this in the default install on HBP systems? Thanks.

2020-07-28 09:15 UTC, pramodk commented
@wvangeit : sure! So py-bluepyefe should be installed on external system as a module?
cc: @jorblancoa

2020-07-28 09:44 UTC, wvangeit commented
@pramodk , yep